# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - misspell
    - stylecheck

linters-settings:
  gosimple:
    go: "1.17"
    checks:
      - "all"
  staticcheck:
    go: "1.17"
    checks:
      - "all"
  stylecheck:
    go: "1.17"
    checks:
      - "all"
      - "-ST1000"
    dot-import-whitelist:
      - github.com/shogo82148/goa-v1/design
      - github.com/shogo82148/goa-v1/design/apidsl
  unused:
    go: "1.17"
