// Code generated by goagen v1.5.10, DO NOT EDIT.
//
// API "goa-sample": Application Media Types
//
// Command:
// $ main

package app

import (
	"time"
)

// User_media media type (default view)
//
// Identifier: application/vnd.user_media+json; view=default
type UserMedia struct {
	// ユーザー作成日時
	CreatedAt time.Time `form:"created_at" json:"created_at" yaml:"created_at" xml:"created_at"`
	// 姓
	FamilyName string `form:"family_name" json:"family_name" yaml:"family_name" xml:"family_name"`
	// 名前
	GivenName string `form:"given_name" json:"given_name" yaml:"given_name" xml:"given_name"`
	// ユーザーID
	UserID int `form:"user_id" json:"user_id" yaml:"user_id" xml:"user_id"`
}

// Validate validates the UserMedia media type instance.
func (mt *UserMedia) Validate() (err error) {

	return
}
